// Sample Application 2
//////////////////////////
//
// DO NOT EDIT THIS FILE !!!
//
//////////////////////////
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "psu_thread.h"


char REMOTE_HOSTNAME[255];

void print_hostname()
{
  char buffer[100];
  int ret;
  if ((ret = gethostname(buffer, sizeof(buffer))) == -1) {
    perror("gethostname");
    exit(1);
  }
  printf("Hostname: %s\n", buffer);
}

void* foo(void* arg)
{
  int a = (int *)arg;
  print_hostname();
  printf("Foo: Value of A = %d\n",a);
  psu_thread_migrate(REMOTE_HOSTNAME);
  print_hostname();
  printf("Foo:Value of A = %d\n",a);
  return NULL;
}

int main(int argc, char* argv[])
{

  if(argc < 3) {
    printf("Waiting for goodbye\n");
    return 0;
  }
  psu_thread_setup_init(atoi(argv[2]));

  strcpy(REMOTE_HOSTNAME, argv[1]);
  psu_thread_create(foo, (void *)10);

  return 0;
}